build.gradle
src/main/java/uk/gov/hmcts/reform/demo/controllers/RootController.java
src/main/java/uk/gov/hmcts/reform/demo/errorhandling/DataStorageNotFoundException.java
src/main/java/uk/gov/hmcts/reform/demo/errorhandling/ExceptionResponse.java
src/main/java/uk/gov/hmcts/reform/demo/errorhandling/GlobalExceptionHandler.java

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-516
```
[ ] Yes
[ x] No
```

Implement global exception handling

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.sbox.template.yaml
config/owasp/suppressions.xml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-529
```
[ ] Yes
[x] No
```

Add changes to Jenkins. pipeline

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-529
Fixed Dependency Check issue + Fixed app starting up issue by switching back to spring 2.3.12.RELEASE
```
[ ] Yes
[x] No
```

PUB-529 - Fixed App and Dependency Check

---

src/main/resources/mocks/courtsAndHearingsCount.json

https://tools.hmcts.net/jira/browse/PUB-888
Added ' to magistrates
```
[ ] Yes
[x] No
```

PUB-888 - Added ' to magistrates

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/CaseEventGlossaryTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/CourtApiTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/GetWelcomeTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/HearingApiTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/LiveCaseStatusApiTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/integrationTest/resources/application-test.yaml
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/CaseEventGlossaryControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/CourtControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/HearingControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/LiveCaseStatusControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/CourtEventGlossaryServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/CourtServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/FilterServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/HearingServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/LiveCaseStatusServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1000
Introduced embedded Postgres into data management and remedied a broken integration test from 945.
This should be functional now, if context issues appear then the line below should be appended to class definition:
_@AutoConfigureEmbeddedDatabase(type_ = AutoConfigureEmbeddedDatabase.DatabaseType.POSTGRES)_
```
[ ] Yes
[x ] No
```

Pub 1000v2 change postgres

---

src/main/resources/mocks/courtsAndHearingsCount.json

https://tools.hmcts.net/jira/browse/PUB-956
added SJP into courts list as it is to be treated as a court and given the id of 0. Confirmed that it does not need a location or jurisdiction
```
[ ] Yes
[x] No
```

Added SJP to courts list

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/HearingApiTest.java
src/integrationTest/resources/data/hearingResponse.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/models/Hearing.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/HearingControllerTest.java

https://tools.hmcts.net/jira/browse/PUB-881
Updated Hearings to return 24hr time fixing 12hr bug.
Updated tests to test time.
```
[ ] Yes
[X] No
```

PUB-881 - Updated hearing to return 24hr time, updated and added tests

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/AzureBlobService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/main/resources/schemas/civil_daily_cause_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/database/AzureBlobServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1045
Updated the /artefact/<artefactId> endpoint, to return the Artefact Metadata (The same as the POST endpoint), rather than the payload.
Added /artefact/<artefactId>/payload, which will return the payload of the artefact.
```
[x] Yes
[ ] No
```

PUB 1045 - Metadata Endpoint

---

charts/pip-data-management/Chart.yaml

https://hmcts-reform.slack.com/archives/C02ECRF7T1R/p1644501458036309
Upgrade Charts versions before AKS cluster upgrade.
```
[ ] Yes
[ X ] No
```

Update Chart version for AKS Upgrade

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/models/court/Court.java

https://tools.hmcts.net/jira/browse/PUB-1111
removed capitalisation manipulation of the imported data

Pub-1111 - capitalisation manipulation of the imported data

---

README.md

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/PUB-1237
README to re-trigger master build
```
[ ] Yes
[ ] No
```

PUB - 1237 - Updated README

---

infrastructure/tf-apim-api.tf

[PUB-1144](https://tools.hmcts.net/jira/browse/PUB-1144)
Convert it from using Swagger+Json to OpenApi+Json
```
[ ] Yes
[ x ] No
```

PUB-1144 - Change from Swagger to Open API

---

infrastructure/resources/api-policy/api-policy.xml
infrastructure/tf-apim-api.tf

JWT is not configured yet so excluding for now.
```
[ ] Yes
[ x ] No
```

Comment out JWT Validation until configured

---

infrastructure/resources/operation-policies/uploadPublicationUsingPOST_1.xml
infrastructure/resources/swagger/api-swagger.json
infrastructure/tf-apim-api.tf
infrastructure/tf-apim-operations.tf

PUB-1144
Add the Subscription Boolean
Add the Get endpoint
Add the backend Service URL
```
[ ] Yes
[ x ] No
```

PUB-1144 - Update sub bool, add get, update backend service URL

---

charts/pip-data-management/values.dev.template.yaml
charts/pip-data-management/values.sbox.template.yaml
charts/pip-data-management/values.yaml
infrastructure/data.tf
infrastructure/main.tf
infrastructure/resources/api-policy/api-policy.xml
infrastructure/tf-db-main.tf
infrastructure/tf-db-secrets.tf
src/main/resources/application.yaml

PUB-1239
Add a Dedicated Database to the Data Management API
```
[ x ] Yes
[ ] No
```

PUB-1239 - Add dedicated database

---

src/integrationTest/resources/data/artefact.json
src/integrationTest/resources/data/civil-daily-cause-list/civilDailyCauseList.json
src/integrationTest/resources/data/civil-daily-cause-list/civilDailyCauseListInvalid.json

N/A
Fix integration tests for Data Management
```
[ ] Yes
[x] No
```

Fix Integration Tests

---

infrastructure/data.tf

remove specific compent name and make dynamic
```
[ ] Yes
[ x ] No
```

remove specific compent name

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationControllerTest.java

https://tools.hmcts.net/jira/browse/PUB-1039
added logging to the upload endpoints
```
[ ] Yes
[x] No
```

added optional header to upload to track manual uploads

---

Jenkinsfile_CNP
Jenkinsfile_parameterized

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

removed flyway from jenkins

---

config/owasp/suppressions.xml
infrastructure/tf-apim-api.tf
infrastructure/tf-db-main.tf

[PUB-1354](https://tools.hmcts.net/jira/browse/PUB-1354)
Resize DB. if staging or prod then use 8 core, else use standard 2 core.
```
[ ] Yes
[ x ] No
```

PUB-1354 - Resize DB

---

config/owasp/suppressions.xml
infrastructure/main.tf

PUB-1409 
remove the env from the base url
```
[ ] Yes
[ x ] No
```

PUB-1409 - correct url for prod

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationApiTest.java
src/functionalTest/resources/location/ValidCsv.csv
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/LocationRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/LocationService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/LocationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1276
- Change court filter so that it can work for Welsh language
- Change court search by name so that it can work for Welsh language
[] Yes
[x] No

PUB 1276 - Welsh filters and court search

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.dev.template.yaml

N/A
Updated Chart
```
[ ] Yes
[x] No
```

Updated chart

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/headers/PublicationUnauthorizedTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1478
Have switched to logging out the user ID or masking the email e.g. test@email.com becomes t***@email.com
```
[ ] Yes
[x] No
```

PUB-1478 Mask logs

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-1536
PUB-1536 Up max file upload limit to 2MB
```
[ ] Yes
[x] No
```

PUB-1536 Increase max file upload limit to 2MB

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/config/WebClientConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/data/management/config/WebClientCreationTest.java

https://tools.hmcts.net/jira/browse/PUB-1521
Changing how client registrations are read in to fix servletRequest cannot be null error.
```
[ ] Yes
[x] No
```

PUB-1521 Service-to-service fix

---

infrastructure/resources/swagger/api-swagger.json
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationEtDailyListTest.java
src/functionalTest/resources/data/et-daily-list/etDailyList.json
src/functionalTest/resources/data/et-daily-list/etDailyListInvalid.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/models/publication/ListType.java
src/main/resources/application.yaml
src/main/resources/schemas/et_daily_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/helpers/JsonHelper.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/EtDailyListTest.java
src/test/resources/mocks/et-daily-list/etDailyList.json

https://tools.hmcts.net/jira/browse/PUB-1320
Schema for tribs daily list and assorted tests. Note: this is pretty much exactly the same as the existing fortnightly tribs list (PUB-1322)
```
[ ] Yes
[x] No
```

PUB-1320 - Tribunal Daily List Schema

---

README.md
infrastructure/resources/swagger/api-swagger.json
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationPrimaryHealthListTest.java
src/functionalTest/resources/data/primary-health-list/primaryHealthList.json
src/functionalTest/resources/data/primary-health-list/primaryHealthListInvalid.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/models/publication/ListType.java
src/main/resources/application.yaml
src/main/resources/schemas/primary_health_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/PrimaryHealthListTest.java
src/test/resources/mocks/primary-health-list/primaryHealthList.json

https://tools.hmcts.net/jira/browse/PUB-1471
Created validation schema for the primary health list.
```
[ ] Yes
[x] No
```

PUB-1471 Primary health list validation schema

---

src/functionalTest/resources/data/iac-daily-list/iacDailyList.json
src/functionalTest/resources/data/iac-daily-list/iacDailyListInvalid.json
src/main/resources/schemas/iac_daily_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/IacDailyListTest.java
src/test/resources/mocks/iac-daily-list/iacDailyList.json

https://tools.hmcts.net/jira/browse/PUB-1346
- Add venue contact as mandatory fields
- Remove court house name and court house contact (pending confirmation from SNL)
```
[ ] Yes
[x] No
```

PUB-1346 Add venue contact to IAC daily list validation schema

---

src/main/resources/schemas/civil_and_family_daily_cause_list.json
src/main/resources/schemas/civil_daily_cause_list.json
src/main/resources/schemas/family_daily_cause_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilAndFamilyDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/FamilyCauseListTest.java

N/A
Add postcode validation back in
```
[ ] Yes
[x] No
```

Add postcode validation back in

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationCrownWarnedListTest.java
src/functionalTest/resources/data/crown-warned-list/crownWarnedList.json
src/functionalTest/resources/data/crown-warned-list/crownWarnedListInvalid.json
src/main/resources/application.yaml
src/main/resources/schemas/crown_warned_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownWarnedListTest.java
src/test/resources/mocks/crown-warned-list/crownWarnedList.json

https://tools.hmcts.net/jira/browse/PUB-1380
Add validation schema for crown warned list
```
[ ] Yes
[x] No
```

Add validation schema for crown warned list

---

build.gradle
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java

Revert master to last PR merged.

Revert master

---

src/functionalTest/resources/data/care-standards-list/careStandardsList.json
src/functionalTest/resources/data/care-standards-list/careStandardsListInvalid.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/main/resources/schemas/care_standards_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CareStandardsListTest.java
src/test/resources/mocks/care-standards-list/careStandardsList.json

https://tools.hmcts.net/jira/browse/PUB-1468
Make changes to schema according to template requirements.
[ ] Yes
[x] No

PUB-1468 Care Standards List Schema changes

---

build.gradle
config/owasp/suppressions.xml

N/A
Updated dependencies + supressions
```
[ ] Yes
[x] No
```

Fix DM pipeline

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationApiTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationController.java

https://tools.hmcts.net/jira/browse/PUB-1618
Secured location endpoints + updated functional tests.
New functional test for unauthorised still required.
```
[ ] Yes
[x] No
```

PUB-1618 - Added security + Updated test

---

src/main/resources/db/migration/V1.1__Sjp_court_load.sql

https://tools.hmcts.net/jira/browse/PUB-1589
Fixed formatting
```
[ ] Yes
[x] No
```

PUB-1589 - Fix formatting

---

build.gradle

Upgrade postgresql dependency to fix CVE-2022-41946
```
[ ] Yes
[x] No
```

CVE-2022-41946 Upgrade postgresql dependency

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/AzureBlobService.java

https://tools.hmcts.net/jira/browse/PUB-1703
Fix the bug in auto blob deletions.
[ ] Yes
[x] No

PUB-1703 Fix Auto Blob Deletion bug

---

build.gradle
config/owasp/suppressions.xml

N/A
Update suppressions
```
[ ] Yes
[x] No
```

Updated Suppressions

---

infrastructure/tf-apim-logger.tf

https://tools.hmcts.net/jira/browse/PUB-1625
Updated IaC code for apim app insights (see ticket for further details).
```
[ ] Yes
[x] No
```

PUB-1625 APIM Logging Updates

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/models/publication/HeaderGroup.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CareStandardsListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilAndFamilyDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CopDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownFirmListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownWarnedListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/EtDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/EtFortnightlyPressList.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/FamilyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/IacDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesStandardListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/PrimaryHealthListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SscsDailyListTest.java

https://tools.hmcts.net/jira/browse/PUB-1625
Added custom logging for when a publications fails, this can store up to 32kb of a payload in the message over the existing 8k.
```
[ ] Yes
[x] No
```

PUB-1625 Added custom logging for failed publications

---

config/owasp/suppressions.xml

N/A
Added suppression due to already being on latest version + part of spring
```
[ ] Yes
[x] No
```

Fixed dependencies

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/CaseEventGlossaryController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/HearingController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/LiveCaseStatusUpdatesController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/ViewController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/CourtsAndHearings.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/models/publication/views/ArtefactView.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/FilterService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/LocationService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractor.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/config/flyway/FlywayNoOpStrategyTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CareStandardsListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilAndFamilyDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CopDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownFirmListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/FamilyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/IacDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesStandardListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/PrimaryHealthListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SscsDailyListTest.java

https://tools.hmcts.net/jira/browse/PUB-1738
Remove code smell for data management repo.
[ ] Yes
[x] No

PUB-1738 Remove code smells

---

build.gradle

Upgrade owasp dependency check to 8.0.2 latest
[ ] Yes
[x] No

Upgrade owasp dependency check

---

.github/workflows/update-pr.yml

https://tools.hmcts.net/jira/browse/PUB-1783
Added new workflow to update PRs with latest destination branch.
```
[ ] Yes
[x] No
```

PUB-1783 - Automate updating with base branch

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1769
Get MI data where location ID is not a number
```
[ ] Yes
[x] No
```

Get MI data where location ID is not a number

---

infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-1675
Re-added the role of the artefact MV.
```
[ ] Yes
[x] No
```

Re added role for MV

---

build.gradle
config/owasp/suppressions.xml

N/A
Updated suppressions
```
[ ] Yes
[x] No
```

Updated gradle + suppressions

---

.github/workflows/ci.yml
build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-1910
Updated dependencies
```
[ ] Yes
[x] No
```

PUB-1910 - Updated dependencies

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationEtDailyListTest.java
src/functionalTest/resources/data/et-daily-list/etDailyList.json
src/functionalTest/resources/data/et-daily-list/etDailyListInvalid.json
src/functionalTest/resources/data/et-fortnightly-press-list/etFortnightlyPressList.json
src/functionalTest/resources/data/et-fortnightly-press-list/etFortnightlyPressListInvalid.json
src/test/resources/mocks/et-daily-list/etDailyList.json
src/test/resources/mocks/et-fortnightly-press-list/etFortnightlyPressList.json

https://tools.hmcts.net/jira/browse/PUB-1925
Updated ET test data
Also updated ET method names
```
[ ] Yes
[x] No
```

PUB-1925 - Updated ET lists

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java

https://tools.hmcts.net/jira/browse/PUB-1632
Functional test for archiveExpiredArtefacts endpoint is modified to test whether the isArchived status is changed or not
```
[ ] Yes
[x] No
```

Functional test for archiveExpiredArtefacts endpoint is modified

---

README.md

https://tools.hmcts.net/jira/browse/PUB-1991
Updated to retrigger build
```
[ ] Yes
[x] No
```

PUB-1991 - Updated to retrigger build

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/database/AzureBlobService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/AccountManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/LocationService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/SubscriptionManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactSearchService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactTriggerService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServicesServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/SubscriptionManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactTriggerServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1732
Update logging
```
[ ] Yes
[x] No
```

PUB-1732 Update logging

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1944
Added further log statements for deleting publications by location
```
[ ] Yes
[x] No
```

PUB-1944 - Added log statements

---

README.md
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationSubscriptionSearchTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/functionalTest/resources/data/artefact.json
src/functionalTest/resources/data/civil-daily-cause-list/civilDailyCauseList.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/config/AdvancedSearchConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/config/PartySearchConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/config/SearchConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactSearchService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/CaseSearchTerm.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractor.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/data/management/helpers/ArtefactConstantTestHelper.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactSearchServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractorTest.java
src/test/resources/mocks/jsonPayloadWithParties.json

https://tools.hmcts.net/jira/browse/PUB-2002
DRAFT
This PR adds the ability to search on parties (Surname + Organisation Name), and will eventually form part of the wider frontend piece of work which lets subscriptions to be created from this
```
[ ] Yes
[x] No
```

PUB-2002 - Subscribe by parties

---

build.gradle
charts/pip-data-management/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-1996
Monthly dependency update
```
[ ] Yes
[x] No
```

PUB-1996 - Updated dependencies

---

README.md
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/config/PartySearchConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractor.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/data/management/utils/JsonExtractorTest.java
src/test/resources/mocks/jsonPayloadWithParties.json

https://tools.hmcts.net/jira/browse/PUB-1945
Return full individual names and organisations in the search value
```
[ ] Yes
[x] No
```

PUB-1945 Return full individual names and organisations in the search value

---

config/owasp/suppressions.xml
src/main/resources/schemas/sscs_daily_list.json
src/test/resources/mocks/sscs-daily-list/sscsDailyList.json

https://tools.hmcts.net/jira/browse/PUB-2009
Allow party organisation in SSCS daily list schema
```
[ ] Yes
[x] No
```

PUB-2009 Allow party organisation in SSCS daily list schema

---

src/main/resources/schemas/single_justice_procedure_press.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java
src/test/resources/mocks/sjp-press-list/sjpPressList.json

https://tools.hmcts.net/jira/browse/PUB-1985
Allow organisation details for accused party
```
[ ] Yes
[x] No
```

PUB-1985 Allow organisation details for accused party

---

build.gradle
config/owasp/suppressions.xml

N/A
Fixed pipeline vulnerability
```
[ ] Yes
[x] No
```

Fixed pipeline vulnerability 

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationSjpPressTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/config/WebConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2054
Add SJP delta press list (new cases)
```
[ ] Yes
[X] No
```

Pub 2054 - Add SJP delta press list

---

infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-1763
Remove Postgres role
```
[ ] Yes
[x] No
```

PUB-1763 Remove postgres role

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/PUB-1763
Enable APIM in Demo
```
[ ] Yes
[x] No
```

PUB-1763 - Add demo into deployed envs

---

src/functionalTest/resources/data/cop-daily-cause-list/copDailyCauseList.json
src/functionalTest/resources/data/cop-daily-cause-list/copDailyCauseListInvalid.json
src/main/resources/schemas/cop_daily_cause_list.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CopDailyCauseListTest.java
src/test/resources/mocks/cop-daily-cause-list/copDailyCauseList.json
src/test/resources/mocks/jsonPayload.json

https://tools.hmcts.net/jira/browse/PUB-2106
Update COP_DAILY_CAUSE_LIST validation schema:
- Removed schemaLocation
- Added courtRoomName and made mandatory
- Updated judiciary for regionalJoh and session -> judiciary
```
[ ] Yes
[x] No
```

PUB-2106 Update COP_DAILY_CAUSE_LIST validation schema

---

infrastructure/providers.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf
infrastructure/tf-db-secrets.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PUB-2130
Created Azure flexible server for postgres 15, storing creds in KV.
```
[ ] Yes
[x] No
```

PUB-2130 Create Postgres 15 Azure Flexible Server

---

infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2157
Add in Azure Extensions to DB

PUB-2157 - Add in Flexible Server extensions

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.yaml

https://tools.hmcts.net/jira/browse/PUB-2192
Changed Managed Identity chart back
```
[ ] Yes
[x] No
```

PUB-2192 - Changed chart back

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.dev.template.yaml
charts/pip-data-management/values.stg.template.yaml
charts/pip-data-management/values.yaml

https://tools.hmcts.net/jira/browse/PUB-2192
Chart Update - Workload Identity
```
[ ] Yes
[x] No
```

PUB-2192 - Chart Update Workload Identity

---

infrastructure/tf-db-main.tf

Removed old role
https://tools.hmcts.net/jira/browse/PUB-2189
```
[ ] Yes
[x] No
```

PUB-2189 - Removed old role

---

infrastructure/tf-db-flexible.tf
infrastructure/tf-db-main.tf
infrastructure/tf-db-secrets.tf

https://tools.hmcts.net/jira/browse/PUB-2189
DB Migration Part 2
```
[ ] Yes
[x] No
```

PUB-2189 - Part 2

---

infrastructure/providers.tf
infrastructure/tf-db-flexible.tf
infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-2222
Remove old postgres config
```
[ ] Yes
[x] No
```

PUB-2222 - Removed old config

---

infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2222
Updated permissions
```
[ ] Yes
[x] No
```

PUB-2222 - Updated permissions

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java

https://tools.hmcts.net/jira/browse/PUB-1851
Updated the java docs on the MI controller endpoints
```
[ ] Yes
[x] No
```

PUB-1851 - Added java docs to the get MI controller

---

build.gradle
config/owasp/suppressions.xml

N/A
Updated dependency check
```
[ ] Yes
[x] No
```

Updated dependency check

---

README.md
charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.yaml

https://tools.hmcts.net/jira/browse/PUB-2245
Updated README + Removed unused chart value
```
[ ] Yes
[x] No
```

PUB-2245 - Updated README

---

.github/workflows/terraform_format.yml
infrastructure/providers.tf
infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2182
Add terraform_format.yml
```
[ ] Yes
[X] No
```

PUB-2182 add terraform_format.yml

---

.github/workflows/terraform_format.yml
README.md
charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.yaml
infrastructure/providers.tf
infrastructure/tf-db-flexible.tf
src/functionalTest/resources/data/magistrates-standard-list/magistratesStandardList.json
src/functionalTest/resources/data/magistrates-standard-list/magistratesStandardListInvalid.json
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactTriggerService.java
src/main/resources/schemas/magistrates_standard_list.json
src/main/resources/schemas/master_schema.json
src/test/resources/mocks/magistrates-standard-list/magistratesStandardList.json

Merge code freeze branch to Master
```
[ ] Yes
[x] No
```

Merge code freeze branch to Master

---

build.gradle
infrastructure/resources/swagger/api-swagger.json
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationOpaResultsTest.java
src/functionalTest/resources/data/opa-results/opaResults.json
src/functionalTest/resources/data/opa-results/opaResultsInvalid.json
src/main/resources/application.yaml
src/main/resources/schemas/master_schema.json
src/main/resources/schemas/opa_results.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CareStandardsListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilAndFamilyDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CivilDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CopDailyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownFirmListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/CrownWarnedListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/EtFortnightlyPressListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/FamilyCauseListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/IacDailyListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/MagistratesStandardListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/OpaPressListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/OpaPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/OpsResultsTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/PrimaryHealthListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPublicListTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SscsDailyListTest.java
src/test/resources/mocks/opa-results/opaResults.json

https://tools.hmcts.net/jira/browse/PUB-2207
Add OPA results validation schema
```
[ ] Yes
[x] No
```

PUB-2207 Add OPA results validation schema

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/ChannelManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2288
Use V2 version of delete publication files endpoint
```
[ ] Yes
[x] No
```

PUB-2288 Use V2 version of delete publication files endpoint

---

infrastructure/resources/swagger/api-swagger.json

https://tools.hmcts.net/jira/browse/PUB-2269
Removed Get Welcome endpoint from publication APIM
```
[ ] Yes
[x] No
```

PUB-2269 Removed Get Welcome endpoint from publication APIM

---

build.gradle
src/main/resources/schemas/care_standards_list.json
src/main/resources/schemas/civil_and_family_daily_cause_list.json
src/main/resources/schemas/civil_daily_cause_list.json
src/main/resources/schemas/cop_daily_cause_list.json
src/main/resources/schemas/crown_daily_list.json
src/main/resources/schemas/crown_firm_list.json
src/main/resources/schemas/crown_warned_list.json
src/main/resources/schemas/et_daily_list.json
src/main/resources/schemas/et_fortnightly_press_list.json
src/main/resources/schemas/family_daily_cause_list.json
src/main/resources/schemas/iac_daily_list.json
src/main/resources/schemas/magistrates_public_list.json
src/main/resources/schemas/magistrates_standard_list.json
src/main/resources/schemas/master_schema.json
src/main/resources/schemas/opa_press_list.json
src/main/resources/schemas/opa_public_list.json
src/main/resources/schemas/opa_results.json
src/main/resources/schemas/primary_health_list.json
src/main/resources/schemas/single_justice_procedure_press.json
src/main/resources/schemas/single_justice_procedure_public.json
src/main/resources/schemas/sscs_daily_list.json

https://tools.hmcts.net/jira/browse/PUB-2278
Update JSON schema version and schema validator dependency
```
[ ] Yes
[x] No
```

PUB-2278 Update JSON schema version and schema validator dependency

---

Jenkinsfile_nightly
README.md
build.gradle
config/fortify-client.properties
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/TestingSupportApiTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/headers/PublicationInternalCourtIdTest.java

https://tools.hmcts.net/jira/browse/PUB-1619
Added Fortify into Data Management

PUB-1619 - Updated fortify

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-2337
Enable graceful shutdown
```
[ ] Yes
[x] No
```

PUB-2337 - Enable graceful shutdown

---

src/functionalTest/resources/data/iac-daily-list/iacDailyList.json
src/functionalTest/resources/data/iac-daily-list/iacDailyListInvalid.json
src/main/resources/schemas/iac_daily_list.json
src/test/resources/mocks/iac-daily-list/iacDailyList.json

https://tools.hmcts.net/jira/browse/PUB-2262
Removing Individual Middle Name from the IAC List
```
[ ] Yes
[x] No
```

PUB-2262: Removing Individual Middle Name from the IAC List

---

src/functionalTest/resources/data/sscs-daily-list/sscsDailyList.json
src/functionalTest/resources/data/sscs-daily-list/sscsDailyListInvalid.json
src/main/resources/schemas/sscs_daily_list.json
src/test/resources/mocks/sscs-daily-list/sscsDailyList.json

https://tools.hmcts.net/jira/browse/PUB-2339
Updated SSCS party role to respondent
```
[ ] Yes
[x] No
```

PUB-2339 - Updated party role for SSCS

---

infrastructure/resources/operation-policies/welcome.xml

https://tools.hmcts.net/jira/browse/PUB-2281
Remove uneeded re-write
```
[ ] Yes
[x] No
```

PUB-2281 - Updated welcome

---

src/main/resources/schemas/civil_and_family_daily_cause_list.json
src/main/resources/schemas/crown_daily_list.json
src/main/resources/schemas/crown_firm_list.json

https://tools.hmcts.net/jira/browse/PUB-2304
Removed unused region and regionalJOH fields
```
[ ] Yes
[x] No
```

PUB-2304 Removed unused region and regionalJOH fields

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/lists/PublicationSjpPressTest.java
src/functionalTest/resources/data/sjp-press-list/sjpPressList.json
src/functionalTest/resources/data/sjp-press-list/sjpPressListInvalid.json
src/main/resources/schemas/single_justice_procedure_press.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java

https://tools.hmcts.net/jira/browse/PUB-2428
SJP Press List - make DOB and age fields optional
```
[ ] Yes
[x] No
```

PUB-2428 SJP Press List DOB and age optional

---

infrastructure/tf-apim-logger.tf

https://tools.hmcts.net/jira/browse/PUB-2183
Updated sampling rates for APIM to 100% and added conditional on request body / response for prod
```
[ ] Yes
[x] No
```

PUB-2183 - Updated Sampling Rate

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationSubscriptionSearchTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactSearchService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/utils/CaseSearchTerm.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/helpers/ArtefactConstantTestHelper.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactSearchServiceTest.java

[https://tools.hmcts.net/jira/browse/<PR-name-here>](https://tools.hmcts.net/jira/browse/PUB-2440)
Removed party name search option
```
[ ] Yes
[x] No
```

PUB-2440 Removed party name search option

---

src/main/resources/schemas/single_justice_procedure_press.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java
src/test/resources/mocks/sjp-press-list/sjpPressList.json

https://tools.hmcts.net/jira/browse/PUB-2459
SJP Press List offence wording schema change
```
[ ] Yes
[x] No
```

PUB-2459 SJP Press List offence wording schema change

---

infrastructure/providers.tf

N/A
Updated azurerm version to fix build
```
[ ] Yes
[x] No
```

Updated azurerm version

---

src/main/resources/schemas/master_schema.json
src/main/resources/schemas/single_justice_procedure_press.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java

https://tools.hmcts.net/jira/browse/PUB-2484
Allow new line characters for SJP Press wording
```
[ ] Yes
[x] No
```

PUB-2484 - Accept new line characters for SJP Press wording

---

src/functionalTest/resources/data/opa-results/opaResults.json
src/functionalTest/resources/data/opa-results/opaResultsInvalid.json
src/main/resources/schemas/master_schema.json
src/main/resources/schemas/opa_results.json
src/test/resources/mocks/opa-results/opaResults.json

https://tools.hmcts.net/jira/browse/PUB-2474
OPA Results - Move offence to individualDetails/organisationDetails level
```
[ ] Yes
[x] No
```

PUB-2474 OPA Results - Move offence to individualDetails/organisationDetails level

---

src/main/resources/schemas/master_schema.json
src/main/resources/schemas/single_justice_procedure_press.json
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/schemavalidation/SjpPressListTest.java

https://tools.hmcts.net/jira/browse/PUB-2486
Update address line for SJP Press to accept \r and \n
```
[ ] Yes
[x] No
```

PUB-2487 - Updated regex for address line

---

src/functionalTest/resources/data/civil-and-family-cause-list/civilAndFamilyDailyCauseList.json
src/functionalTest/resources/data/civil-and-family-cause-list/civilAndFamilyDailyCauseListInvalid.json
src/functionalTest/resources/data/cop-daily-cause-list/copDailyCauseList.json
src/functionalTest/resources/data/cop-daily-cause-list/copDailyCauseListInvalid.json
src/functionalTest/resources/data/family-daily-cause-list/familyDailyCauseList.json
src/functionalTest/resources/data/family-daily-cause-list/familyDailyCauseListInvalid.json
src/functionalTest/resources/data/hearing-party/civilAndFamilyDailyCauseList.json
src/functionalTest/resources/data/hearing-party/civilAndFamilyDailyCauseListInvalid.json
src/functionalTest/resources/data/hearing-party/familyDailyCauseList.json
src/functionalTest/resources/data/hearing-party/familyDailyCauseListInvalid.json
src/main/resources/schemas/civil_and_family_daily_cause_list.json
src/main/resources/schemas/cop_daily_cause_list.json
src/main/resources/schemas/family_daily_cause_list.json
src/test/resources/mocks/civil-and-family-cause-list/civilAndFamilyDailyCauseList.json
src/test/resources/mocks/cop-daily-cause-list/copDailyCauseList.json
src/test/resources/mocks/family-daily-cause-list/familyDailyCauseList.json
src/test/resources/mocks/hearing-party/civilAndFamilyDailyCauseList.json
src/test/resources/mocks/hearing-party/familyDailyCauseList.json

https://tools.hmcts.net/jira/browse/PUB-2448
Add case reporting restrictions for Family, Mixed and COP lists
```
[ ] Yes
[x] No
```

PUB-2448 Add case reporting restrictions for Family, Mixed and COP lists

---

src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationCreationRunner.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteService.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationCreationRunnerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/PublicationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactDeleteServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/artefact/ArtefactServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2509
Stop generating search criteria for payload over limit
```
[ ] Yes
[x] No
```

PUB-2509 Stop generating search criteria for payload over limit

---

src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/CivilAndFamilyCauseListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/CopCauseListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/CrownDailyListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/CrownFirmListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/EtFortnightlyPressListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/FamilyCauseListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/MagistratesPublicListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/MagistratesStandardListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/SjpPressListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/SscsDailyListFileConverterTest.java

https://tools.hmcts.net/jira/browse/PUB-2551
Removed unneeded spring boot test annotations 
```
[ ] Yes
[x] No
```

PUB-2551 - Remove unneeded spring boot test annotation

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.yaml

https://tools.hmcts.net/jira/browse/PUB-2549
Fixed blob storage
```
[ ] Yes
[x] No
```

Updated blob storage

---

charts/pip-data-management/Chart.yaml
charts/pip-data-management/values.dev.template.yaml
charts/pip-data-management/values.yaml

https://tools.hmcts.net/jira/browse/PUB-2549
Updated blob storage
```
[ ] Yes
[x] No
```

Updated blobstorage

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/location/LocationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/publication/FileGenerationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/publication/PublicationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/utils/FunctionalTestBase.java
src/functionalTest/resources/application-functional.yaml

https://tools.hmcts.net/jira/browse/PUB-2661
Added further functional tests for Data Management
```
[ ] Yes
[x] No
```

PUB-2661 - Added Functional tests

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/LocationApiTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationManagementTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationSubscriptionSearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/utils/IntegrationTestBase.java
src/integrationTest/resources/application-integration.yaml

https://tools.hmcts.net/jira/browse/PUB-2660
Mock account-management service for data-management integration tests
```
[ ] Yes
[x] No
```

PUB-2660 Mock account-management service for data-management integration tests

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/database/ArtefactRepository.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/publication/PublicationService.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/helpers/ArtefactConstantTestHelper.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/publication/PublicationServiceTest.java

Reverts hmcts/pip-data-management#660

Revert "PUB-2249 - MI Models"

---

build.gradle
infrastructure/resources/swagger/api-swagger.json
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2712
Add CIC Daily Hearing List
```
[ ] Yes
[x] No
```

PUB-2712 Add CIC Daily Hearing List 

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/NonStrategicPublicationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/PublicationTest.java

Moved out non-strategic publication integration tests
```
[ ] Yes
[x] No
```

Moved out non-strategic publication integration tests

---

src/smokeTest/java/uk/gov/hmcts/reform/pip/data/management/SmokeTest.java
src/smokeTest/java/uk/gov/hmcts/reform/pip/data/management/utils/SmokeTestBase.java

https://tools.hmcts.net/jira/browse/PUB-2776
Fixed issue with test data not removed after smoke tests
```
[ ] Yes
[x] No
```

PUB-2776 Fixed issue with test data not removed after smoke tests

---

infrastructure/tf-db-flexible.tf

CHG5020830
Removed invalid extension
```
[ ] Yes
[x] No
```

Removed invalid extension

---

src/main/resources/templates/languages/cy/non-strategic/countyCourtLondonCivilDailyCauseList.json
src/main/resources/templates/languages/cy/non-strategic/mayorAndCityCivilDailyCauseList.json
src/main/resources/templates/languages/en/non-strategic/countyCourtLondonCivilDailyCauseList.json
src/main/resources/templates/languages/en/non-strategic/mayorAndCityCivilDailyCauseList.json
src/main/resources/templates/non-strategic/countyCourtLondonCivilDailyCauseList.html
src/main/resources/templates/non-strategic/mayorAndCityCivilDailyCauseList.html
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/nonstrategic/CountyCourtLondonCivilDailyCauseListFileConverterTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/service/filegeneration/nonstrategic/MayorAndCityCivilDailyCauseListFileConverterTest.java

https://tools.hmcts.net/jira/browse/PUB-2922
Update open justice statement for Mayor and County courts
```
[ ] Yes
[x] No
```

PUB-2922 - Updated open justice statement

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/location/LocationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/pip/data/management/publication/PublicationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/location/LocationApiTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/controllers/publication/PublicationSearchTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/location/LocationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/publication/PublicationController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/publication/PublicationReportingController.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/controllers/publication/PublicationSearchController.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/location/LocationControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/data/management/controllers/publication/PublicationSearchControllerTest.java

https://tools.hmcts.net/jira/browse/PUB-2969
Update data-management endpoints to use query parameters
```
[ ] Yes
[x] No
```

PUB-2969 Update data-management endpoints to use query parameters

---

build.gradle
infrastructure/resources/swagger/api-swagger.json
src/integrationTest/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationServiceTest.java
src/main/java/uk/gov/hmcts/reform/pip/data/management/service/ValidationService.java

https://tools.hmcts.net/jira/browse/PUB-2965
Removed CIC Daily Hearing List
```
[ ] Yes
[x] No
```

PUB-2965 - Removed CIC Daily Hearing List
